"""Typed Pydantic models for TradingView webhook payloads."""

# Pylint: pydantic models are data containers by design
# pylint: disable=R0903

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Optional
from pydantic import BaseModel, ConfigDict


class General(BaseModel):
    """General metadata about the alert and timing."""

    model_config = ConfigDict(extra="ignore")

    strategy: Optional[str] = None
    ticker: str
    interval: str
    time: datetime
    timenow: datetime
    secret: Optional[str] = None
    leverage: Optional[str] = None


class Currency(BaseModel):
    """Currency pair details (only base is consumed)."""

    model_config = ConfigDict(extra="ignore")

    base: str


class Order(BaseModel):
    """Order instruction generated by the strategy."""

    model_config = ConfigDict(extra="ignore")

    action: str
    contracts: Decimal
    price: Decimal
    id: str
    comment: Optional[str] = None
    alert_message: Optional[str] = None


class Market(BaseModel):
    """Market context around current and previous positions."""

    model_config = ConfigDict(extra="ignore")

    position: str
    position_size: Decimal
    previous_position: str
    previous_position_size: Decimal


class TradingViewWebhook(BaseModel):
    """Top-level TradingView webhook payload."""

    model_config = ConfigDict(extra="ignore")

    general: General
    currency: Currency
    order: Order
    market: Market
